### ISSUE TITLE
Methods 'toRads', 'changeVelocity', and 'resetGame' do not exist

### ISSUE THREAD

**Issue by MrDiamondDog** [jyoung4242/Pong-HathoraPeasy#1]
![image](https://user-images.githubusercontent.com/84212701/180667855-011d9899-ab59-402d-904e-2b90ff16d99f.png)
Unmodified code straight from the repository.

**Comment by jyoung4242** [comment]
these files are located in helper.ts, and if they weren't pulled in, this error will happen

**Comment by jyoung4242** [comment]
i believe the included file solved the issue
